import { analyzeFrequencies } from "../../tools/frequencyAnalysis/frequencyAnalysis";
import { bingoList_v10_4 } from "./__testData__/bingoList_v10_4";
import { standardProfile } from "./__testData__/standardProfile";

describe("frequencyAnalysis", () => {
  const consoleSpy = jest.spyOn(console, "log");

  beforeEach(() => {
    consoleSpy.mockReset();
  });

  it("performs a correct frequency analysis on 75 normal 10.4 boards", async () => {
    const frequencyResult = await analyzeFrequencies(bingoList_v10_4, 75, "normal");

    const expectedFrequencyResult = {
      meta: {
        iterations: {
          max: 16,
          average: 4.347,
        },
        attempts: {
          successes: 75,
          fails: 0,
          total: 75,
        },
      },
      frequencies: {
        "30 Different Skulltulas": 52,
        "All 3 Elemental Arrows": 48,
        "Open All 6 Gold Rupee Chests": 43,
        "Both Rusty Switches in Spirit Temple": 42,
        "Clear 10 Silver Rupee Rooms": 40,
        "Green Gauntlets": 36,
        "3 Swords, Tunics, Boots, and Shields": 31,
        "9 Hearts (no duping)": 29,
        "All 5 Skulltulas in Water Temple": 23,
        "Fill 20 Item Inventory Slots": 23,
        "Defeat Meg (Purple Poe)": 22,
        "1 Skulltula from each Adult Dungeon": 20,
        "Minuet of Forest": 20,
        "Quiver (50)": 20,
        "Obtain all 5 Small Keys in Shadow Temple": 20,
        "All 3 Skulltulas in Bottom of the Well": 19,
        "3 Skulltulas in Water Temple": 18,
        "Din's Fire": 17,
        "Goron Bracelet": 17,
        "Exactly 30 Deku Sticks": 17,
        "All 5 Skulltulas in Fire Temple": 17,
        "All 8 Death Mountain area Skulltulas": 15,
        "4 Skulltulas in Shadow Temple": 15,
        "Goron Tunic": 15,
        "5 Zora area HPs": 15,
        "Double Defense": 14,
        "Obtain 16 Different Heart Pieces": 14,
        "Map & Compass in Jabu-Jabu": 14,
        "8 Hearts (no duping)": 14,
        "Win Bombchu Bowling Prize": 14,
        "All 4 Market area Skulltulas": 13,
        "Map & Compass in Bottom of the Well": 13,
        "Free all 9 Gorons in Fire Temple": 13,
        "5 Hearts": 13,
        "All 5 Lake Hylia Skulltulas": 13,
        "Open Forest Temple Boss Key Door": 13,
        "Beat the Spirit Temple": 13,
        "10 Songs": 13,
        "All 5 Skulltulas in Shadow Temple": 13,
        "All 8 Zora's Domain area Skulltulas": 12,
        "Obtain all 5 Small Keys in Forest Temple": 12,
        "Gerudo's Card": 12,
        "All 4 Wasteland/ Colossus area Skulltulas": 12,
        "Nayru's Love": 12,
        "Obtain 4 Different Heart Containers": 12,
        "Lens of Truth": 12,
        "Giant's Knife": 11,
        "Keaton Mask": 11,
        "Defeat Twinrova": 11,
        "Clear 8 Silver Rupee Rooms": 11,
        "Open 3 Gold Rupee Chests": 11,
        "3 Swords & 3 Tunics": 11,
        "Obtain 12 Different Heart Pieces": 11,
        "Defeat 4 Different Iron Knuckles": 11,
        "Saria's Song": 11,
        "All 4 Child Zora's Domain area Skulltulas": 11,
        "Open 5 Gold Rupee Chests": 11,
        "Biggoron's Sword": 11,
        "3 Shields & 3 Boots": 11,
        "Bolero of Fire": 10,
        "All 4 Lon Lon Ranch area Skulltulas": 10,
        "Map & Compass in Forest Temple": 10,
        "All 8 Kakariko area Skulltulas": 10,
        "All 4 Skulltulas in Jabu-Jabu": 10,
        "Bottled Fairy": 10,
        "Defeat King Dodongo": 10,
        "20 Different Skulltulas": 10,
        "Bronze Gauntlets": 10,
        "Zora Tunic": 10,
        "Defeat both Flare Dancers": 10,
        "Defeat Dark Link": 9,
        "Beat the Water Temple": 9,
        "Both HPs in Death Mountain Crater": 9,
        "Open the Final Door of Shadow Trial": 9,
        "3 Lake Hylia Skulltulas": 9,
        "Giant's Wallet": 9,
        "Ganon's Castle Boss Key": 9,
        "4 Unused Keys in Forest Temple": 9,
        "All 4 Skulltulas in Deku Tree": 9,
        "Map & Compass in Shadow Temple": 9,
        "Quiver (40)": 9,
        "8 Songs": 9,
        "Open 50 Rupee chest in Wasteland": 9,
        Boomerang: 8,
        "Both Hyrule Field area Skulltulas": 8,
        "8 Different Unused Keys in Gerudo Training Grounds": 8,
        "Beat Jabu-Jabu's Belly": 8,
        "Frog's HP": 8,
        Milk: 8,
        "Fire Temple Boss Key": 8,
        "Lon Lon Ranch HP": 8,
        "All 4 Lost Woods area Skulltulas": 8,
        "7 Magic Beans": 8,
        "Cow in House": 8,
        "Defeat all Lizalfos in Dodongo's Cavern": 8,
        "Blue Potion": 8,
        "All 5 Skulltulas in Spirit Temple": 8,
        "Obtain all 8 Small Keys in Fire Temple": 8,
        "All 4 Gerudo Valley area Skulltulas": 8,
        "All 5 Skulltulas in Forest Temple": 8,
        "Defeat Big Octo": 8,
        "Map & Compass in Dodongo's Cavern": 7,
        "7 Compasses": 7,
        "Bullet Bag (50)": 7,
        "Open the Final Door of Fire Trial": 7,
        "Forest Temple Boss Key": 7,
        "Plant bean in Death Mountain Crater": 7,
        "7 Different Unused Keys in Gerudo Training Grounds": 7,
        "Two Fairy Spells": 7,
        "Beat the Shadow Temple": 7,
        "Desert Colossus HP": 7,
        "Plant 5 Magic Beans": 7,
        "Bomb Bag (30)": 7,
        "3 Tunics": 7,
        "Defeat Volvagia": 7,
        "All 4 Adult Zora's Domain area Skulltulas": 7,
        "Fairy Slingshot": 6,
        "1 Skulltula from each Child Dungeon": 6,
        "Fairy Bow": 6,
        "500 Rupees": 6,
        Longshot: 6,
        "Open the Final Door of Spirit Trial": 6,
        "3 Swords & 3 Shields": 6,
        "Open the Final Door of Light Trial": 6,
        "Open the Final Door of Forest Trial": 6,
        "Defeat Barinade": 6,
        "2 Skulltulas in Lon Lon Ranch": 6,
        "Defeat a Skull Kid": 6,
        "Ice Cavern HP": 6,
        "Map & Compass in Fire Temple": 6,
        "Double Magic": 6,
        "All 3 Kokiri Forest area Skulltulas": 5,
        "6 Hearts": 5,
        "Light Arrows": 5,
        "Map & Compass in Water Temple": 5,
        "Open the Final Door of Water Trial": 5,
        "Get Bombchu chest in Spirit Temple": 5,
        "Fire Medallion": 5,
        "Map & Compass in Spirit Temple": 5,
        "1 Unused Small Key in each Adult Dungeon": 5,
        "Golden Gauntlets": 5,
        "All 5 Skulltulas in Dodongo's Cavern": 5,
        "5 Magic Beans": 5,
        "Water Temple Boss Key": 5,
        "Silver Scale": 5,
        "Bullet Bag (40)": 4,
        "Both Gerudo Valley HPs": 4,
        "Silver Gauntlets": 4,
        "3 Songs": 4,
        "15 Different Skulltulas": 4,
        "Shadow Temple Boss Key": 4,
        "30 Deku Nuts": 4,
        "Beat the Fire Temple": 4,
        "6 Compasses": 4,
        "37th Heart Piece (Child Fortress)": 4,
        "7 Hearts (no duping)": 4,
        "Epona's Song": 4,
        "Beat Dodongo's Cavern": 4,
        "Fire Arrows": 4,
        "Exactly 20 Deku Sticks": 4,
        "3 Tunics & 3 Boots": 4,
        "Water Medallion": 4,
        "5 Compasses": 4,
        "4 Songs": 4,
        "3 Swords & 3 Boots": 4,
        "Stone of Agony": 4,
        "Megaton Hammer": 4,
        "Blue Fire": 4,
        "Defeat Bongo-Bongo": 4,
        "Requiem of Spirit": 4,
        "Ruto's Letter": 4,
        "3 Shields & 3 Tunics": 3,
        "6 Songs": 3,
        "3 Unused Keys in Gerudo Training Grounds": 3,
        "Beat the Deku Tree": 3,
        "3 Boots": 3,
        "9 Songs": 3,
        "Spirit Temple Boss Key": 3,
        "Open 3 Boss Key Doors": 3,
        "Obtain 3 Different Heart Containers": 3,
        "Farore's Wind": 3,
        "Defeat Queen Gohma": 3,
        "Map & Compass in Deku Tree": 3,
        "Iron Boots": 3,
        "6 Different Unused Keys in Gerudo Training Grounds": 3,
        "4 Compasses": 3,
        "3 Shields": 3,
        "5 Unused Keys in Gerudo Training Grounds": 3,
        "7 Different Bottled Contents": 3,
        "4 Unused Keys in Gerudo Training Grounds": 3,
        "Map & Compass in Ice Cavern": 3,
        "Blue Gauntlets": 2,
        "Defeat Nabooru-Knuckle": 2,
        "Defeat a White Wolfos": 2,
        "7 Maps": 2,
        "Fill all 4 Bottle Slots": 2,
        "Both Gerudo's Fortress area Skulltulas": 2,
        "Defeat Morpha": 2,
        "Mirror Shield": 2,
        "6 Maps": 2,
        "Beat the Forest Temple": 2,
        "Forest Medallion": 1,
        "Clear 4 Silver Rupee Rooms": 1,
        "2 Boss Keys": 1,
        "3 Boss Keys": 1,
        "7 Songs": 1,
        "Defeat 10 Different Stalfos": 1,
        "Defeat Amy (Green Poe)": 1,
      },
    };

    expect(frequencyResult).toStrictEqual(expectedFrequencyResult);
    // Frequencies in right order
    expect(Object.keys(frequencyResult.frequencies)).toStrictEqual(
      Object.keys(expectedFrequencyResult.frequencies),
    );
  });

  it("performs a correct frequency analysis on 75 short 10.4 boards", async () => {
    const frequencyResult = await analyzeFrequencies(bingoList_v10_4, 75, "short");

    const expectedFrequencyResult = {
      meta: {
        iterations: {
          max: 3,
          average: 1.307,
        },
        attempts: {
          successes: 75,
          fails: 0,
          total: 75,
        },
      },
      frequencies: {
        "Get Bombchu chest in Spirit Temple": 44,
        "Map & Compass in Bottom of the Well": 39,
        "Magic Bar": 39,
        "8 Magic Beans": 39,
        "4 Maps": 38,
        "2 Skulltulas in Lon Lon Ranch": 37,
        "6 Hearts": 35,
        "Open 3 Gold Rupee Chests": 33,
        "Double Magic": 33,
        "Defeat a Skull Kid": 33,
        Hookshot: 32,
        "Plant 7 Magic Beans": 32,
        "20 Deku Sticks": 32,
        "Gerudo's Card": 31,
        "4 Compasses": 30,
        "1 Skulltula from each Child Dungeon": 30,
        "99 Rupees": 29,
        "Bullet Bag (50)": 29,
        "All 7 Child Kakariko area Skulltulas": 27,
        "Lost Dog HP": 27,
        "Skull Mask": 26,
        "All 4 Lon Lon Ranch area Skulltulas": 25,
        "All 4 Skulltulas in Deku Tree": 25,
        "6 Unused Keys in Gerudo Training Grounds": 25,
        "Golden Scale": 25,
        "7 Different Bottled Contents": 24,
        "Ruto's Letter": 24,
        "Win Bombchu Bowling Prize": 24,
        "Goron's Ruby": 23,
        "Plant 6 Magic Beans": 23,
        "Green Potion": 22,
        "All 4 Child Zora's Domain area Skulltulas": 22,
        "Plant bean in Death Mountain Crater": 22,
        "Saria's Song": 22,
        "Bullet Bag (40)": 22,
        "Red Potion": 21,
        "Both HPs in Death Mountain Crater": 20,
        "5 Magic Beans": 20,
        "30 Deku Sticks": 20,
        "All 3 Skulltulas in Bottom of the Well": 20,
        "Map & Compass in Deku Tree": 20,
        "15 Different Skulltulas": 20,
        "6 Magic Beans": 19,
        "30 Deku Nuts": 19,
        "Defeat Queen Gohma": 19,
        "7 Magic Beans": 19,
        "Fairy Slingshot": 18,
        "Beat Dodongo's Cavern": 18,
        "Both Child Kokiri Forest area Skulltulas": 18,
        "Defeat all Lizalfos in Dodongo's Cavern": 18,
        "Both Hyrule Field area Skulltulas": 18,
        "Beat Jabu-Jabu's Belly": 18,
        "Plant 3 Magic Beans": 18,
        "Zora's Sapphire": 18,
        "Fairy Ocarina": 17,
        "Lon Lon Ranch HP": 17,
        "Bottled Fairy": 17,
        "All 5 Child Death Mountain area Skulltulas": 16,
        "Silver Scale": 16,
        "Map & Compass in Jabu-Jabu": 16,
        "Open 50 Rupee Chest in Wasteland": 16,
        "Bottled Poe": 16,
        "Fill all 4 Bottle Slots": 16,
        "200 Rupees": 15,
        Boomerang: 15,
        "5 Unused Keys in Gerudo Training Grounds": 15,
        "Both Child Lost Woods area Skulltulas": 15,
        "4 Unused Keys in Gerudo Training Grounds": 14,
        "Defeat Big Octo": 14,
        "Ganon's Castle Boss Key": 14,
        "Adult's Wallet": 14,
        "Plant 4 Magic Beans": 14,
        "Defeat Barinade": 13,
        "Epona's Song": 13,
        Milk: 13,
        "5 Hearts": 12,
        "Keaton Mask": 12,
        "Both Child Wasteland/ Colossus area Skulltulas": 12,
        "37th Heart Piece (Child Fortress)": 12,
        "All 5 Skulltulas in Dodongo's Cavern": 12,
        "Both Gerudo Valley HPs": 11,
        "Defeat a White Wolfos": 11,
        "All 3 Child Lake Hylia Skulltulas": 10,
        "All 4 Skulltulas in Jabu-Jabu": 10,
        "Map & Compass in Dodongo's Cavern": 9,
        "Requiem of Spirit": 8,
        "Plant 5 Magic Beans": 8,
        "3 Unused Keys in Gerudo Training Grounds": 8,
        "Bomb Bag (30)": 7,
        "Both Child Gerudo Valley area Skulltulas": 6,
        "Defeat King Dodongo": 5,
        "Kokiri's Emerald": 5,
        "2 Unused Keys in Gerudo Training Grounds": 5,
        "Ice Arrows": 5,
        "3 Maps": 3,
        "Blue Fire": 2,
        "Beat the Deku Tree": 2,
      },
    };

    expect(frequencyResult).toStrictEqual(expectedFrequencyResult);
    // Frequencies in right order
    expect(Object.keys(frequencyResult.frequencies)).toStrictEqual(
      Object.keys(expectedFrequencyResult.frequencies),
    );
  });

  it("performs a correct frequency analysis on 75 normal 10.1 boards with a start seed", async () => {
    const frequencyResult = await analyzeFrequencies(
      bingoList_v10_4,
      75,
      "normal",
      123456,
    );

    const expectedFrequencyResult = {
      meta: {
        iterations: {
          max: 16,
          average: 3.867,
        },
        attempts: {
          successes: 75,
          fails: 0,
          total: 75,
        },
      },
      frequencies: {
        "Open All 6 Gold Rupee Chests": 51,
        "Both Rusty Switches in Spirit Temple": 48,
        "30 Different Skulltulas": 42,
        "All 3 Elemental Arrows": 40,
        "Clear 10 Silver Rupee Rooms": 36,
        "3 Swords, Tunics, Boots, and Shields": 34,
        "9 Hearts (no duping)": 34,
        "Green Gauntlets": 26,
        "Defeat Meg (Purple Poe)": 24,
        "Din's Fire": 23,
        "All 5 Skulltulas in Water Temple": 23,
        "Fill 20 Item Inventory Slots": 20,
        "Biggoron's Sword": 20,
        "All 5 Lake Hylia Skulltulas": 20,
        "Quiver (50)": 19,
        "8 Hearts (no duping)": 19,
        "5 Hearts": 19,
        "Obtain all 5 Small Keys in Shadow Temple": 18,
        "Free all 9 Gorons in Fire Temple": 18,
        "All 8 Death Mountain area Skulltulas": 17,
        "All 5 Skulltulas in Fire Temple": 16,
        "Ganon's Castle Boss Key": 16,
        "1 Skulltula from each Adult Dungeon": 16,
        "Goron Tunic": 16,
        "Goron Bracelet": 16,
        "Beat the Spirit Temple": 16,
        "Zora Tunic": 16,
        "All 4 Market area Skulltulas": 16,
        "Clear 8 Silver Rupee Rooms": 15,
        "20 Different Skulltulas": 15,
        "Map & Compass in Spirit Temple": 15,
        "3 Skulltulas in Water Temple": 14,
        "All 8 Zora's Domain area Skulltulas": 14,
        "All 3 Skulltulas in Bottom of the Well": 14,
        "Bomb Bag (30)": 14,
        "Map & Compass in Jabu-Jabu": 13,
        "Beat the Water Temple": 13,
        "5 Zora area HPs": 13,
        "All 4 Wasteland/ Colossus area Skulltulas": 13,
        "Open 5 Gold Rupee Chests": 12,
        "Keaton Mask": 12,
        "Nayru's Love": 12,
        "All 4 Gerudo Valley area Skulltulas": 12,
        "Map & Compass in Forest Temple": 12,
        "Open Forest Temple Boss Key Door": 12,
        "Minuet of Forest": 11,
        "Lens of Truth": 11,
        "Map & Compass in Water Temple": 11,
        "Ruto's Letter": 11,
        "All 5 Skulltulas in Shadow Temple": 11,
        "8 Different Unused Keys in Gerudo Training Grounds": 11,
        "3 Shields & 3 Boots": 11,
        "7 Magic Beans": 11,
        "Win Bombchu Bowling Prize": 11,
        "Bolero of Fire": 11,
        "Open 50 Rupee chest in Wasteland": 10,
        "Double Defense": 10,
        "All 4 Lost Woods area Skulltulas": 10,
        "Obtain all 8 Small Keys in Fire Temple": 10,
        "Exactly 20 Deku Sticks": 10,
        "Obtain 16 Different Heart Pieces": 10,
        "Defeat 4 Different Iron Knuckles": 10,
        "Fill all 4 Bottle Slots": 10,
        "Bullet Bag (40)": 10,
        "Saria's Song": 10,
        "3 Swords & 3 Tunics": 10,
        "10 Songs": 10,
        "Lon Lon Ranch HP": 10,
        "Quiver (40)": 10,
        "Defeat both Flare Dancers": 10,
        "Giant's Knife": 10,
        "1 Unused Small Key in each Adult Dungeon": 10,
        "Silver Scale": 10,
        "3 Lake Hylia Skulltulas": 10,
        "All 3 Kokiri Forest area Skulltulas": 9,
        Longshot: 9,
        "Obtain 4 Different Heart Containers": 9,
        "3 Tunics": 9,
        "Map & Compass in Dodongo's Cavern": 9,
        "7 Compasses": 9,
        "500 Rupees": 9,
        "Obtain all 5 Small Keys in Forest Temple": 9,
        "Fire Temple Boss Key": 9,
        "Defeat Big Octo": 9,
        "All 8 Kakariko area Skulltulas": 9,
        "Defeat Barinade": 9,
        "Both Gerudo Valley HPs": 9,
        "Defeat all Lizalfos in Dodongo's Cavern": 8,
        "Open the Final Door of Spirit Trial": 8,
        "Defeat a Skull Kid": 8,
        "All 4 Adult Zora's Domain area Skulltulas": 8,
        "All 4 Child Zora's Domain area Skulltulas": 8,
        "Two Fairy Spells": 8,
        "3 Swords & 3 Shields": 8,
        "Both HPs in Death Mountain Crater": 8,
        "Exactly 30 Deku Sticks": 8,
        "2 Skulltulas in Lon Lon Ranch": 7,
        "Beat the Shadow Temple": 7,
        "Double Magic": 7,
        "30 Deku Nuts": 7,
        "7 Different Unused Keys in Gerudo Training Grounds": 7,
        Boomerang: 7,
        "All 5 Skulltulas in Forest Temple": 7,
        "Plant bean in Death Mountain Crater": 7,
        "All 4 Lon Lon Ranch area Skulltulas": 7,
        "4 Skulltulas in Shadow Temple": 7,
        "Plant 5 Magic Beans": 7,
        "Gerudo's Card": 7,
        "Fire Arrows": 7,
        "Light Arrows": 7,
        "All 5 Skulltulas in Dodongo's Cavern": 7,
        "Map & Compass in Fire Temple": 6,
        "Defeat Bongo-Bongo": 6,
        "15 Different Skulltulas": 6,
        "Farore's Wind": 6,
        "Cow in House": 6,
        "Golden Gauntlets": 6,
        "Bullet Bag (50)": 6,
        "1 Skulltula from each Child Dungeon": 6,
        "Mirror Shield": 6,
        "Beat Dodongo's Cavern": 6,
        "3 Shields": 6,
        "3 Swords & 3 Boots": 6,
        "Open the Final Door of Forest Trial": 6,
        "Defeat Phantom Ganon": 6,
        "Defeat Volvagia": 6,
        "6 Hearts": 6,
        "Defeat Morpha": 6,
        "3 Shields & 3 Tunics": 5,
        "Frog's HP": 5,
        "Open the Final Door of Fire Trial": 5,
        "5 Magic Beans": 5,
        "5 Unused Keys in Gerudo Training Grounds": 5,
        "Beat Jabu-Jabu's Belly": 5,
        "Map & Compass in Bottom of the Well": 5,
        "Bottled Fairy": 5,
        "Open the Final Door of Water Trial": 5,
        "All 3 Skulltulas in Ice Cavern": 5,
        "Beat the Forest Temple": 5,
        "Ice Cavern HP": 5,
        "Desert Colossus HP": 5,
        "7 Songs": 5,
        "Open 3 Gold Rupee Chests": 5,
        "All 4 Skulltulas in Jabu-Jabu": 5,
        "Iron Boots": 5,
        "Forest Temple Boss Key": 5,
        "Both Hyrule Field area Skulltulas": 5,
        "4 Unused Keys in Forest Temple": 5,
        "37th Heart Piece (Child Fortress)": 5,
        "Beat the Deku Tree": 5,
        "Epona's Song": 5,
        "Obtain 12 Different Heart Pieces": 4,
        "Defeat King Dodongo": 4,
        "Bronze Gauntlets": 4,
        "Map & Compass in Deku Tree": 4,
        "9 Songs": 4,
        "Water Medallion": 4,
        "3 Tunics & 3 Boots": 4,
        Milk: 4,
        "Fire Medallion": 4,
        "Map & Compass in Ice Cavern": 4,
        "Blue Potion": 4,
        "Open the Final Door of Shadow Trial": 4,
        "All 5 Skulltulas in Spirit Temple": 4,
        "6 Compasses": 4,
        "4 Compasses": 3,
        "Defeat Dark Link": 3,
        "7 Hearts (no duping)": 3,
        "Open the Final Door of Light Trial": 3,
        "8 Songs": 3,
        "Both Gerudo's Fortress area Skulltulas": 3,
        "Defeat Nabooru-Knuckle": 3,
        "Spirit Temple Boss Key": 3,
        "All 4 Skulltulas in Deku Tree": 3,
        "Open 3 Boss Key Doors": 3,
        "Open 2 Boss Key Doors": 3,
        "Defeat Queen Gohma": 3,
        "7 Maps": 3,
        "Megaton Hammer": 3,
        "3 Boots": 3,
        "Stone of Agony": 3,
        "3 Unused Keys in Gerudo Training Grounds": 3,
        "Shadow Temple Boss Key": 3,
        "Defeat Amy (Green Poe)": 3,
        "5 Compasses": 3,
        "Water Temple Boss Key": 3,
        "Fairy Bow": 3,
        "6 Different Unused Keys in Gerudo Training Grounds": 3,
        "Obtain 3 Different Heart Containers": 3,
        "Clear 4 Silver Rupee Rooms": 2,
        "Ice Arrows": 2,
        "Defeat Twinrova": 2,
        "7 Different Bottled Contents": 2,
        "Blue Fire": 2,
        "4 Songs": 2,
        "3 Songs": 2,
        "Fairy Slingshot": 2,
        "Requiem of Spirit": 2,
        "Beat the Fire Temple": 2,
        "3 Boss Keys": 2,
        "Defeat 10 Different Stalfos": 2,
        "Get Bombchu chest in Spirit Temple": 1,
        "Map & Compass in Shadow Temple": 1,
        "Blue Gauntlets": 1,
        "Giant's Wallet": 1,
        "4 Unused Keys in Gerudo Training Grounds": 1,
        "Silver Gauntlets": 1,
        "6 Maps": 1,
        "Forest Medallion": 1,
      },
    };

    expect(frequencyResult).toStrictEqual(expectedFrequencyResult);
    // Frequencies in right order
    expect(Object.keys(frequencyResult.frequencies)).toStrictEqual(
      Object.keys(expectedFrequencyResult.frequencies),
    );
  });

  it(
    "logs the process while calculating the frequencies",
    async () => {
      await analyzeFrequencies(bingoList_v10_4, 1000, "normal", 123456);

      expect(consoleSpy).toHaveBeenNthCalledWith(
        1,
        "Analyzing goal frequency of 1000 boards, with mode normal, starting from seed 123456...",
      );
      expect(consoleSpy).toHaveBeenNthCalledWith(
        2,
        "Generating... (processed 500 boards)",
      );
      expect(consoleSpy).toHaveBeenNthCalledWith(
        3,
        expect.stringMatching(
          /Finished, generated 1000 boards in [0-9]+(\.[0-9]+)?s \(average iterations = 4\.513\)\n/,
        ),
      );
    },
    1000 * 60,
  );

  it("does not include failed boards in the final count", async () => {
    const frequencyResult = await analyzeFrequencies(
      bingoList_v10_4,
      2,
      "normal",
      123456,
      1,
      // impossible to generate
      {
        ...standardProfile,
        minimumSynergy: 4,
        maximumSynergy: 3,
      },
    );

    expect(consoleSpy).toHaveBeenNthCalledWith(
      1,
      "Analyzing goal frequency of 2 boards, with mode normal, starting from seed 123456...",
    );
    expect(consoleSpy).toHaveBeenNthCalledWith(
      2,
      expect.stringMatching(
        /Finished, generated 0 boards in [0-9]+(\.[0-9]+)?s \(average iterations = 100 \(including 2 failed boards\)\)\n/,
      ),
    );
    expect(frequencyResult.meta).toEqual({
      attempts: {
        fails: 2,
        successes: 0,
        total: 2,
      },
      iterations: {
        average: 100,
        max: 100,
      },
    });
  });

  it("pretty prints the frequencies", async () => {
    await analyzeFrequencies(bingoList_v10_4, 100, "normal", 123456);

    expect(consoleSpy).toHaveBeenNthCalledWith(
      1,
      "Analyzing goal frequency of 100 boards, with mode normal, starting from seed 123456...",
    );
    expect(consoleSpy).toHaveBeenNthCalledWith(
      2,
      expect.stringMatching(
        /Finished, generated 100 boards in [0-9]+(\.[0-9]+)?s \(average iterations = 3\.97\)\n/,
      ),
    );
    expect(consoleSpy).toHaveBeenNthCalledWith(3, "META\n------------");
    expect(consoleSpy).toHaveBeenNthCalledWith(4, "Iterations - Max: 16, Average: 3.97");
    expect(consoleSpy).toHaveBeenNthCalledWith(
      5,
      "Attempts - Successes: 100, Fails: 0, Total: 100",
    );
    expect(consoleSpy).toHaveBeenNthCalledWith(6, "\nGOAL FREQUENCIES\n------------");
    expect(consoleSpy).toHaveBeenNthCalledWith(
      7,
      "Both Rusty Switches in Spirit Temple: 67\nOpen All 6 Gold Rupee Chests: 64\n30 Different Skulltulas: 57\nAll 3 Elemental Arrows: 55\nClear 10 Silver Rupee Rooms: 46\n3 Swords, Tunics, Boots, and Shields: 43\n9 Hearts (no duping): 43\nGreen Gauntlets: 35\nAll 5 Skulltulas in Water Temple: 34\nDefeat Meg (Purple Poe): 33\nDin's Fire: 31\nFill 20 Item Inventory Slots: 29\nAll 8 Death Mountain area Skulltulas: 27\nQuiver (50): 26\nGoron Bracelet: 26\nAll 5 Lake Hylia Skulltulas: 26\nObtain all 5 Small Keys in Shadow Temple: 25\nAll 5 Skulltulas in Fire Temple: 24\nBiggoron's Sword: 24\n1 Skulltula from each Adult Dungeon: 23\n8 Hearts (no duping): 23\n5 Hearts: 23\nFree all 9 Gorons in Fire Temple: 21\nBeat the Spirit Temple: 21\nGanon's Castle Boss Key: 20\n5 Zora area HPs: 20\nBolero of Fire: 20\nObtain all 8 Small Keys in Fire Temple: 19\nMap & Compass in Spirit Temple: 19\nQuiver (40): 19\nClear 8 Silver Rupee Rooms: 18\n20 Different Skulltulas: 18\nAll 4 Market area Skulltulas: 18\nAll 3 Skulltulas in Bottom of the Well: 18\nWin Bombchu Bowling Prize: 18\nMinuet of Forest: 17\nMap & Compass in Jabu-Jabu: 17\n3 Skulltulas in Water Temple: 17\nAll 5 Skulltulas in Shadow Temple: 17\nGoron Tunic: 17\nZora Tunic: 17\nAll 4 Gerudo Valley area Skulltulas: 17\nBomb Bag (30): 17\nLens of Truth: 16\nAll 4 Wasteland/ Colossus area Skulltulas: 16\nOpen Forest Temple Boss Key Door: 16\nOpen 5 Gold Rupee Chests: 15\nSaria's Song: 15\nTwo Fairy Spells: 15\n3 Shields & 3 Boots: 15\nMap & Compass in Forest Temple: 15\nObtain 4 Different Heart Containers: 14\n8 Different Unused Keys in Gerudo Training Grounds: 14\n10 Songs: 14\nNayru's Love: 14\nAll 8 Zora's Domain area Skulltulas: 14\nGiant's Knife: 14\n7 Magic Beans: 14\nAll 3 Kokiri Forest area Skulltulas: 13\n2 Skulltulas in Lon Lon Ranch: 13\nKeaton Mask: 13\nMap & Compass in Water Temple: 13\nExactly 20 Deku Sticks: 13\nObtain 16 Different Heart Pieces: 13\nBeat the Water Temple: 13\nMap & Compass in Dodongo's Cavern: 13\n3 Swords & 3 Tunics: 13\nDefeat Barinade: 13\nSilver Scale: 13\nOpen 50 Rupee chest in Wasteland: 12\nDouble Defense: 12\nAll 4 Lost Woods area Skulltulas: 12\nDefeat 4 Different Iron Knuckles: 12\nRuto's Letter: 12\nFill all 4 Bottle Slots: 12\n500 Rupees: 12\nDefeat a Skull Kid: 12\nAll 4 Adult Zora's Domain area Skulltulas: 12\nFire Temple Boss Key: 12\nLon Lon Ranch HP: 12\nBoth HPs in Death Mountain Crater: 12\nLongshot: 11\nBullet Bag (40): 11\nObtain all 5 Small Keys in Forest Temple: 11\nAll 5 Skulltulas in Forest Temple: 11\nAll 4 Child Zora's Domain area Skulltulas: 11\nDefeat Big Octo: 11\nDefeat both Flare Dancers: 11\nAll 8 Kakariko area Skulltulas: 11\n1 Unused Small Key in each Adult Dungeon: 11\nAll 4 Lon Lon Ranch area Skulltulas: 11\n3 Swords & 3 Shields: 11\nGerudo's Card: 11\n4 Unused Keys in Forest Temple: 11\n3 Tunics: 10\nDefeat all Lizalfos in Dodongo's Cavern: 10\nPlant bean in Death Mountain Crater: 10\n4 Skulltulas in Shadow Temple: 10\n3 Lake Hylia Skulltulas: 10\nAll 5 Skulltulas in Dodongo's Cavern: 10\nBeat the Shadow Temple: 9\nDouble Magic: 9\nOpen the Final Door of Spirit Trial: 9\n7 Compasses: 9\nBoomerang: 9\nCow in House: 9\nGolden Gauntlets: 9\nAll 3 Skulltulas in Ice Cavern: 9\nPlant 5 Magic Beans: 9\nBoth Gerudo Valley HPs: 9\nOpen the Final Door of Forest Trial: 9\nOpen 3 Gold Rupee Chests: 9\nFire Arrows: 9\nAll 4 Skulltulas in Jabu-Jabu: 9\nExactly 30 Deku Sticks: 9\nDefeat Morpha: 9\nMap & Compass in Fire Temple: 8\n30 Deku Nuts: 8\nFarore's Wind: 8\nOpen the Final Door of Fire Trial: 8\nBeat Dodongo's Cavern: 8\nForest Temple Boss Key: 8\nBlue Potion: 8\nBeat the Deku Tree: 8\nObtain 3 Different Heart Containers: 8\nEpona's Song: 8\n5 Magic Beans: 7\n7 Different Unused Keys in Gerudo Training Grounds: 7\nDefeat King Dodongo: 7\nBullet Bag (50): 7\n1 Skulltula from each Child Dungeon: 7\n3 Tunics & 3 Boots: 7\nDesert Colossus HP: 7\n3 Swords & 3 Boots: 7\n7 Songs: 7\nLight Arrows: 7\nDefeat Volvagia: 7\nBoth Hyrule Field area Skulltulas: 7\nDefeat 10 Different Stalfos: 7\nDefeat Bongo-Bongo: 6\n15 Different Skulltulas: 6\nObtain 12 Different Heart Pieces: 6\n5 Unused Keys in Gerudo Training Grounds: 6\nBeat Jabu-Jabu's Belly: 6\nBottled Fairy: 6\nOpen the Final Door of Water Trial: 6\nDefeat Twinrova: 6\nMirror Shield: 6\nIce Cavern HP: 6\n3 Shields: 6\nFire Medallion: 6\nIron Boots: 6\nDefeat Phantom Ganon: 6\n6 Hearts: 6\nOpen the Final Door of Shadow Trial: 6\nFairy Bow: 6\n3 Shields & 3 Tunics: 5\nFrog's HP: 5\nClear 4 Silver Rupee Rooms: 5\nMap & Compass in Bottom of the Well: 5\nDefeat Dark Link: 5\n7 Hearts (no duping): 5\n9 Songs: 5\nBoth Gerudo's Fortress area Skulltulas: 5\n7 Different Bottled Contents: 5\nSpirit Temple Boss Key: 5\nBeat the Forest Temple: 5\nAll 4 Skulltulas in Deku Tree: 5\nDefeat Queen Gohma: 5\nMilk: 5\n7 Maps: 5\nMegaton Hammer: 5\n3 Boots: 5\nShadow Temple Boss Key: 5\nDefeat Amy (Green Poe): 5\nWater Temple Boss Key: 5\n37th Heart Piece (Child Fortress): 5\nAll 5 Skulltulas in Spirit Temple: 5\n6 Compasses: 5\n4 Compasses: 4\nGet Bombchu chest in Spirit Temple: 4\nOpen the Final Door of Light Trial: 4\nBronze Gauntlets: 4\nMap & Compass in Deku Tree: 4\nWater Medallion: 4\nStone of Agony: 4\nMap & Compass in Ice Cavern: 4\n3 Unused Keys in Gerudo Training Grounds: 4\n5 Compasses: 4\n8 Songs: 3\nDefeat Nabooru-Knuckle: 3\nOpen 3 Boss Key Doors: 3\nOpen 2 Boss Key Doors: 3\n3 Songs: 3\nGiant's Wallet: 3\nRequiem of Spirit: 3\n6 Different Unused Keys in Gerudo Training Grounds: 3\n3 Boss Keys: 3\nIce Arrows: 2\nBlue Fire: 2\nMap & Compass in Shadow Temple: 2\nBlue Gauntlets: 2\n4 Songs: 2\nFairy Slingshot: 2\n4 Unused Keys in Gerudo Training Grounds: 2\nBeat the Fire Temple: 2\n6 Maps: 2\nSilver Gauntlets: 1\nForest Medallion: 1\n6 Songs: 1\n",
    );
  });
});
